languageCode = "en-us"
title = "GeenPeil Techblog"
baseurl = "https://techblog-dev.geenpeil.nl/"
theme = "geenpeil"
copyright = "&copy; GeenPeil"

[params]
  piwikHostname = "analytics-dev.geenpeil.nl"
